#! /bin/sh

# Verifica se o sxhkd está rodando {{{

pgrep -x sxhkd > /dev/null || sxhkd & 

# }}} 

# Inicialização {{{

~/.config/bspwm/autostart.sh
~/.config/bspwm/rulesbspwm.sh

# }}}

# Bspc configs {{{

# Monitores Workspace {{{

bspc monitor DisplayPort-0 -d 1 2 3 4 # 1 monitor
bspc monitor HDMI-A-0 -d 5 6 7 8 # 2 monitor

# }}}

# borda / gap {{{

bspc config border_width         2
# bspc config border_width_out 4
# bspc config border_width_in 4
bspc config window_gap           0

# }}}

# cores borda {{{

# bspc config normal_border_color "#1a1b26"
bspc config normal_border_color "#1a1b26"
# bspc config focused_border_color "#7aa2f7"
bspc config focused_border_color "#1a1b26"

# }}}

# split / monocle {{{

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config double_monocle       true

# }}}

# end Bspc config }}}
