#! /bin/sh

# Verifica se o sxhkd está rodando {{{
pgrep -x sxhkd > /dev/null || sxhkd & # }}}

# Config init {{{
#xrandr --output DisplayPort-0 xrandr --output DisplayPort-0 --primary --mode 1366x768 --rotate normal --output HDMI-A-0 --mode 1024x768 --rotate normal --right-of DisplayPort-0
xrandr --output DisplayPort-0 --primary
xrandr --output HDMI-A-0 --right-of DisplayPort-0
xrandr --output DisplayPort-0 --brightness 1.2
setxkbmap -layout br -option caps:swapescape &
~/.fehbg &
# picom &
# picom  
~/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr &
conky -c ~/.config/conky/Mintaka/Mintaka.conf &
xrdb ~/.Xresources# }}}

# Bspc configs {{{

# 1 monitor
bspc monitor DisplayPort-0 -d 1 2 3 4
# 2 monitor
bspc monitor HDMI-A-0 -d 5 6 7 8

bspc config border_width         2
# bspc config border_width_out 4
# bspc config border_width_in 4
bspc config window_gap           1

bspc config normal_border_color "#b3b3b3"
bspc config focused_border_color "#FFFFFF"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true# }}}

# Bspc Rules {{{
# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^6' focus=on
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
bspc rule -a firefox desktop='^5' focus=on
bspc rule -a discord desktop='^8' follow=off


# }}}
