#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#xrandr --output DisplayPort-0 xrandr --output DisplayPort-0 --primary --mode 1366x768 --rotate normal --output HDMI-A-0 --mode 1024x768 --rotate normal --right-of DisplayPort-0
xrandr --output DisplayPort-0 --primary
xrandr --output HDMI-A-0 --right-of DisplayPort-0
xrandr --output DisplayPort-0 --brightness 1.2
setxkbmap -layout br -option caps:swapescape &
~/.fehbg &
picom &
~/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr &

bspc monitor DisplayPort-0 -d 1 2 3 4
bspc monitor HDMI-A-0 -d 5 6 7 8

bspc config border_width         1
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
